name: Archive and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set file name
        run: echo "FILENAME=Fast-Install-${{ github.ref_name }}.apbx" >> $GITHUB_ENV
      
      - name: Archive content
        run: |
          7z a -p${{ secrets.PASSWORD }} -mhe=on "${{ env.FILENAME }}" ./*
      
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ${{ env.FILENAME }}
          asset_name: ${{ env.FILENAME }}
          tag: ${{ github.ref }}
          overwrite: true